- comments.php
- wp-discourse.php
Added SSO functions
Publish to Discourse with WP Category
> SSO and Category

- js/discourse.js
- wp-discourse.php
ref https://github.com/discourse/wp-discourse/pull/94#issuecomment-68659273
> Move JS from separate file to inline

- wp-discourse.php
Add spaces to be consistent with code formatting for commit
e2bf46a0556751ac630defa3ebd60fac07f3687d
> Add spaces to be consistent with code formatting

- lib/admin.php
@techAPJ you merge fast ;) here's a little cleanup from the last PR
> Minor cleanup after#102

- lib/discourse.php
- wp-discourse.php
> Fixes for #105

- lib/admin.php
Prevent topics like this: https://meta.discourse.org/t/sso-on-a-wp-publish-from-another-wp/25558/2 
:sunglasses:
> Trimming the whitespaces

- lib/admin.php
Fixes bugs introduced on #120
I'm not sure how to deal with default options while hiding unwanted fields without refactoring a good part of the code, so for now things will remain as they were.
> Display default settings because otherwise is kind of buggy

- lib/admin.php
> whitespaces should be stripped only on strings

- lib/discourse.php
see: https://meta.discourse.org/t/wordpress-integration-guide/27531/5
and: https://make.wordpress.org/plugins/2015/04/20/fixing-add_query_arg-and-remove_query_arg-usage/
> fix security issue

- lib/discourse.php
not sure how this ever worked for anyone since the query vars are not set up yet when the parse_request action hook fires.
this fixes #115 for me.
> fix sso login

- lib/discourse.php
This is a more standard way of accessing remote resources than
`file_get_contents`. Some hosting providers turn off the
`allow_url_fopen` option, limiting using this plugin properly.
> Use wp_remote functions instead of file_get_contents

- lib/discourse.php
This will handle the failure gracefully while not completely hiding debugging information.
> Add a log entry when HTTP request fails

- CHANGELOG.md
- lib/discourse.php
- wp-discourse.php
> Version 0.6.6

- lib/discourse.php
If a WP post is updated and has already been published
to Discourse, update the Discourse post with the new post
content or generated excerpt.
Closes #151
> Update Discourse post on WP post update

- .mention-bot
I get the intent behind using @mention-bot but I'd rather not be notified anymore by it. Thanks.
> Add .mention-bot config file

- css/admin-styles.css
- lib/admin.php
> Post Submit misc publishing section

- js/comments.js
This PR brings `comments.js` into compliance with the wp coding standards.
> WordPress coding standards comments.js

- wp-discourse.php
This PR brings `wp-discourse.php` into compliance with the wp coding standards.
> WordPress coding standards wp-discourse.php

- css/admin-styles.css
This PR brings `admin-styles.css` into compliance with the wp coding standards.
> WordPress coding standards admin-styles.css

- lib/discourse.php
- lib/sso.php
This PR brings the file `sso.php` into compliance with the wp coding standards.
> WordPress coding standards sso.php

- lib/response-validator.php
This PR gets `response-validator.php` in compliance with the WordPress coding standards.
> WordPress coding standards response-validator.php

- lib/discourse-comment.php
See https://github.com/discourse/wp-discourse/issues/242 for a derailed discussion.
(LOL - also for a deTailed discussion)
> Fix regression in show existing WP comments feature

- lib/discourse-sso.php
Add filter to allow themes/plugins to hook into the SSO params to add/adjust fields - such as add_groups/remove_groups
> Add filter for SSO Payload Params

- admin/sso-settings.php
The relevant Discourse option is called `sso allows all return paths`
> Update on-page instructions to match reality

- lib/discourse-publish.php
> Added `featured_link` as param

- lib/discourse-comment-formatter.php
- templates/html-templates.php
Echos are missing to enable the "Open Links in New Tab" feature.
> Open links in new tab fix

- admin/css/admin-styles.css
- admin/form-helper.php
- admin/publish-settings.php
- lib/discourse-publish.php
- readme.txt
- tests/phpunit/test-discourse-publish.php
- wp-discourse.php
@scossar Details to follow on meta
> FEATURE: Add tag publishing feature and move to new hook in instances >= WP 5.6

- .github/workflows/deploy.yml
See https://github.com/10up/action-wordpress-plugin-deploy#deploy-on-pushing-a-new-tag. @scossar We'll discuss further on meta.discourse.org
> Create deploy.yml based on the 10up example

- README.md
- admin/admin-menu.php
- admin/configurable-text-settings.php
- admin/form-helper.php
- admin/log-viewer.php
- admin/network-options.php
- admin/options-page.php
- admin/settings-validator.php
- admin/sso-settings.php
- admin/webhook-settings.php
- lib/shortcodes/sso-client.php
- lib/sso-provider/discourse-sso.php
- lib/utilities.php
- readme.txt
- wp-discourse.php
See further https://meta.discourse.org/t/sso-to-discourseconnect/183377
> Apply DiscourseConnect copy changes && new shortcode

- docs/COMPOSER.md
- docs/TESTS.md
- lib/discourse-comment.php
- lib/discourse-publish.php
- lib/plugin-utilities.php
- lib/sso-client/client.php
- lib/sso-provider/discourse-sso.php
- lib/sync-discourse-topic.php
- lib/utilities.php
- readme.txt
- tests/phpunit/helpers/remote_post.php
- tests/phpunit/multisite/test-discourse-publish-multisite.php
- tests/phpunit/test-discourse-comment.php
- tests/phpunit/test-discourse-publish.php
- tests/phpunit/test-discourse-sso.php
- tests/phpunit/test-utilities.php
- wp-discourse.php
- Add Wordpress 5.9 support.
- Complete wp_remote_request standardisation.
- Add method checks to all request tests.
> Wordpress 5.9 support, request standardisation and unit test improvements.

- .github/workflows/deploy.yml
- .github/workflows/formatting.yml
- .github/workflows/metadata.yml
- .github/workflows/tests.yml
- lib/discourse-comment-formatter.php
- lib/discourse-comment.php
- readme.txt
- tests/phpunit/test-discourse-comment-formatter.php
- tests/phpunit/test-discourse-comment.php
- wp-discourse.php
Remove logger call causing issues on some sites.
> Fixes for comment formatter log issue

- admin/admin.php
- admin/log-viewer.php
- admin/options-page.php
- lib/discourse-base.php
- lib/discourse.php
- lib/logs/logger.php
- lib/plugin-utilities.php
- readme.txt
- tests/phpunit/test-discourse-comment-formatter.php
- tests/phpunit/test-discourse-comment.php
- tests/phpunit/test-discourse-publish.php
- tests/phpunit/test-file-handler.php
- tests/phpunit/test-log-viewer.php
- tests/phpunit/test-logger.php
- tests/phpunit/test-sync-discourse-topic.php
- tests/phpunit/test-sync-discourse-user.php
- tests/phpunit/unit-test.php
- wp-discourse.php
- Improve logs metafile handling
- Add logs enabled setting
> Two Four Eight

- .github/workflows/deploy.yml
- .github/workflows/formatting.yml
- .github/workflows/metadata.yml
- .github/workflows/tests.yml
1. Updated actions
2. Updated node to the latest LTS
3. Ran a yaml linter
4. Enabled npm caching
5. Disabled metadata checks for PRs that only update `.github` directory, or package.json/package-lock.json files
> DEV: Update CI workflows

- readme.txt
- wp-discourse.php
Version 2.5.0
- Post publishing code improvements
- PHPUnit updated to PHPUnit 9
This branch is currently live on https://wp-discourse.pavilion.tech/
> Two Five Zero

- lib/wp-new-user-notification.php
Context https://meta.discourse.org/t/new-user-activation-link-doesnt-work-when-activating-discourse-wp-plugin/292670?u=angus
This branch is currently live on wp-discourse.pavilion.tech.
> Update wp_new_user_notification override to latest core version

- lib/sso-provider/discourse-sso.php
See further: https://meta.discourse.org/t/php-deprecated-notice-for-parse-str/312589
> Only parse query_string if it exists

- readme.txt
- wp-discourse.php
- Various improvements to webhooks, including email matching for Update Userdata webhook.
- PHP 8.1 deprecations.
- Don't require existing wp comments to show wp comments with setting.
Live on https://wp-discourse.pavilion.tech
> Two Five Four

- lib/discourse-comment-formatter.php
Adds filter discussed [here](https://meta.discourse.org/t/template-hook-for-discourse-plugin-join-discussion-link-section/323878/8)
> Add wpdc_join_discussion_link_html filter

- readme.txt
- wp-discourse.php
- Security updates.
- Add wpdc_join_discussion_link_html filter.
- Current Wordpress (`6.3.3`) testing and support.
> Two Five Five

- readme.txt
- wp-discourse.php
- Security updates.
- Fix incorrect auto-publish of quick edits.
> Two Five Six

- lib/discourse-publish.php
- readme.txt
- wp-discourse.php
- Updated publish post meta fields storage approach.
- Wordpress 6.8.1 support.
> Two Five Nine
