discourse/wp-discourse

css/style.css
wp-discourse.php

This extra request is unnecessary. Not only was the stylesheet blank, but in a typical workflow you'd never want to edit files from a 3rd party plugin on your WP site. 
If there was going to be some default styling included, this file should stay. But if there's not going to be any included styles, then users will add styling to their WordPress theme instead of editing plugin files.

Remove unnecessary stylesheet

---

wp-discourse.php

Origin: 9dc6085cf52bd02f96b52d8c2200f584e02b3e0e
Fix: #92
When “Published category ” setting is null, get the category of
Wordpress Article and post as publish-category to
Discourse.

Resend: Publish to Discourse with WP Category

---

lib/discourse.php

Updated to use preg_match instead of DOM to get the avatar url.
Added utf8_uri_encode to fix that SSO failed with avatar in Unicode URL.

Updated the function of getting avatar url

---

lib/admin.php

I tweaked how settings page looks like:
- splitted related fields into sections (API settings, Publishing settings and so on)
- added „the WordPress way” of fields style (to have a more unified aspect across all settings within a WP)
- if the api key or URL is not filled, do not display the whole form
This doesn't change any other behavior.
Screenshot: http://i.imgur.com/Ujd79Ys.png

Settings tweaks

---

lib/admin.php

Categories are now fetched from remote, so instead of a text field, we will display a dropdown.
I'm not sure yet why empty categories are not displayed, but it's surely something on Discourse end...

Categories are now fetched from remote

---

lib/admin.php
lib/discourse.php

1. Removed a redundant single quotation mark.
2. Updated to get the discourse options from allowed_post_types

Fixes for allowed post types

---

lib/discourse.php

A previous PR #114 (see also context in #113) added a function to convert relative img src URLs to absolute. Unfortunately, for me, it also turned already absolute URLs into *absoluter* ones, which broke them.
I added a test to the function to see if the URL was already absolute and if so, not do any conversion.
While I was at it, I tweaked the original search regex to escape a couple of naked forward slashes, which I think was wrong. On my setup (using Discourse version 1.3.0.beta4), media URL's in comments are already coming over as absolute, so I cannot directly test that this still correctly converts relative URLs to absolute, but I think it should.

Fix comment img urls

---

templates/comments.php

wordpress was stripping out the <time> tag from the discourse comment html resulting in the date-time meta html not being formatted correctly. this patch just allows the <time> tag to be included in the comment html.

add <time> tag to WP allowed html tags

---

lib/admin.php
lib/discourse.php

This patch is my answer to what to do about enabling Discourse comments for existing posts/pages that have a lot of valuable pre-existing WP comments on them. The prior behavior of the plugin makes you choose to either show Discourse comments and hide the old WP comments OR show the WP comments and not show the Discourse comments. This patch lets you choose to show the existing WP comments as a "historical archive" beneath the new Discourse comments.
In the admin:
I wrapped the "Existing Comments Heading" in a `<div>` with a class of `discourse-existing-comments-heading` so it is easy to style it with css to fit your theme.
On the front end:

Allow showing existing WP comments under Discourse

---

lib/admin.php
templates/comments.php

Allows user to provide a custom datetime formatting string for the comment meta datatime (basically allows inclusion of the time since the original version of this was only including the date).

add custom datetime format string to admin settings

---

lib/discourse.php

if using WP for SSO, add a URL of the form "http://my-wp-blog.com/?request=logout" in the "logout redirect" field in your Discourse admin and when a user logs out from Discourse they will also be logged out of WP

log out of WP when log out of Discourse

---

templates/comments.php

Discourse (properly) sends the timestamp for posts/comments back to wordpress as UTC. The plugin needs to convert to the blog's local timezone before displaying it.

fix timezone for custom timestamp

---

lib/discourse.php

As of WordPress 4.2, there is now a built in get_avatar_url function. Removed custom function and rewritten to use WordPress function.

Replace Avatar URL Function

---

lib/admin.php
lib/discourse.php

Displays a select menu in Publish post metabox
containing Discourse categories
Cleans up code from
https://github.com/PaxInstruments/wp-discourse/commit/c8745d0671a62586bffa01611f68067c4239afe4
Submitted in place of https://github.com/discourse/wp-discourse/pull/175#issuecomment-173940826

Allow choosing Discourse category per post

---

js/comments.js
lib/admin.php
lib/discourse.php
wp-discourse.php

`wp_enqueue_scripts` should absolutely be used instead of including a script directly through `wp_footer`.
The default publishing username should be `system` instead of nothing. I think sometimes users don't realize they should fill out that field. When it's blank and the user hasn't filled out a Discourse username in their profile, then publishing fails.
Default posts types should just be post. People typically don't allow comments on pages.

Better method for including comments script and other small tweaks

---

lib/discourse.php

Calling `add_query_arg` without arguments produces the following notice when `'WP_DEBUG'` is set to `true`:
```
Notice: Undefined offset: 0 in /Users/scossar/testeleven/wp-mamp/wordpress/wp-includes/functions.php on line 772
Notice: Undefined offset: 0 in /Users/scossar/testeleven/wp-mamp/wordpress/wp-includes/functions.php on line 812
Notice: Undefined offset: 0 in /Users/scossar/testeleven/wp-mamp/wordpress/wp-includes/functions.php on line 817
Notice: Undefined offset: 1 in /Users/scossar/testeleven/wp-mamp/wordpress/wp-includes/functions.php on line 817
```
The desired output is `$_SERVER['REQUEST_URI']`. This can be achieved by calling `add_query_arg( NULL, NULL )`

call add_query_arg() with NULL, NULL as arguments

---

lib/discourse.php

With `'WP_DEBUG'` set to `true`, logging in from Discourse when there is a logged in WordPress user produces this notice:
```
Notice: get_currentuserinfo is deprecated since version 4.5! Use wp_get_current_user() instead. in /Users/scossar/testeleven/wp-mamp/wordpress/wp-includes/functions.php on line 3658
```
`wp_get_current_user` is a wrapper of `get_currentuserinfo` using the global variable `$current_user`

use wp_get_current_user

---

lib/discourse.php

When `'WP_DEBUG'` is set to 'true' and `'Show Existing WP Comments'` is set to `false` on the WordPress Discourse settings page,  this notice is generated: `Undefined index: show-existing-comments in /Users/scossar/testeleven/wp-mamp/wordpress/wp-content/plugins/wp-discourse/lib/discourse.php on line 329 `. 
This is fixed by adding the key value pair `'show-existing-comments' => 0` to the options array.

FIX: add show-existing-comments option

---

lib/admin.php
templates/comments.php

When `'WP_DEBUG'` is set to `true` and there are Discourse comments available for a WordPress post, this notice is generated: `Undefined property: stdClass::$name in /Users/scossar/testeleven/wp-mamp/wordpress/wp-content/plugins/wp-discourse/templates/comments.php on line 68`
Line 68 of the comments template is trying to access the `name` property on the `participants` array. The available properties are `username` and `avatar_template`.  This fix deletes the line that references the `name` property. It also removes the `{fullname}` tag from the list of available tags for the participants template.

FIX: name property not available in participants array

---

lib/admin.php

Currently, when there is an error with the `api key` or `publishing username` settings, the `get_discourse_categories` method is generating the notice: 'Undefined index: category_list'. This is happening because a `WP_Error` isn't being generated. This PR adds a check for the status code of the response.
If the force update setting is enabled, and there is an error, and there are cached categories, this PR returns those categories. Previously, the cached categories were being passed through `wp_remote_retrieve_body` and `json_decode` and `set_transient`.
~~In the case where there is an error, but no cache, I'm just returning `null` instead of returning the value stored in `$remote`.~~

FIX: use cached categories when there is a configuration error

---

lib/admin.php

Adds a `type` argument to the `text_input` method. The type defaults to `text`.
Sets the url input type to `url`.
Sets the number input types to `number`.

add type argument to text input method

---

templates/comments.php

Sanitizes data for the comment template. Limits allowed tags in comments to the wordpress allowed post tags.

WIP: sanitize comment template output

---

lib/admin.php

Sanitizes output on the admin options page.
It also removes the empty option tag from the category_select input.

WIP: sanitize admin options page

---

lib/admin.php

Hooks into the `load-settings(page)` action to test the supplied api credentials (url, api-key, username).
Adds success and warning messages to indicate the connection status.

WIP: add notices to indicate connection status

---

css/admin-styles.css
lib/admin.php
lib/discourse.php
lib/settings-validator.php
wp-discourse.php

Adds a SettingsValidator class. The settings are invoked by a call to `apply_filters( $filter, $input );` from `DiscourseAdmin#discourse_validate_options`. Error messages are added to the settings page to give the user a bit of feedback:
I would like to add some tests for the validation. I want to make sure that this work is on the right track before I do that.
I have changed the plugin's text domain from `discourse` to `wp-discourse`.

WIP: validate settings

---

lib/admin.php
lib/discourse.php
lib/html-templates.php
templates/comments.php
wp-discourse.php

Based on this commit to the 10up fork of wp-discourse: https://github.com/10up/wp-discourse/commit/5c9d43c4333e136204d5a3b07192f4b368c3f518
This PR moves the html templates out of the plugin's options. If this is implemented, html templates will no longer be customizable through the options page. They can be customized through the theme using the filters that are applied to each function. A link to the documentation of how to do that is added to the settings page. Here is a tentative version: <https://github.com/scossar/wp-discourse/wiki/Template-Customization>
This PR also changes the plugin's text-domain from `discourse` to `wp-discourse`.

WIP: Move templates out of options

---

lib/admin.php

Don't escape the link in the api key description.
We want this:
Not this:

FIX: allow link in api key description

---

.mention-bot

JSON only supports double quotes for strings.
Sorry about the bot bothering you again @retlehs and @tnorthcutt. This *should* fix it.

Updated to valid JSON formatting

---

lib/discourse.php

Sanitize the 'existing comments heading' with `wp_kses_post`.

FIX: Escape existing comments heading

---

lib/discourse.php

The 'Min number of replies' setting has confused a few users (including me.) This PR sets the default value for the 'Min number of replies' setting to 1.
See https://meta.discourse.org/t/comments-not-being-embedded-in-wordpress-plugin/40345/12?u=simon_cossar and
https://meta.discourse.org/t/discourse-wordpress-plugin-version-0-6-6/31585/27?u=simon_cossar

Change min-replies default to 1

---

css/admin-styles.css
lib/admin.php
lib/discourse.php
lib/plugin-support/woocommerce_support.php
lib/settings-validator.php
wp-discourse.php

Allows Discourse to be used for WooCommerce product reviews.
- ~~Adds a 'plugin support' section to the settings page, with an 'Enable WooCommerce Support' setting~~
- Adds a 'login-path' setting to the settings page SSO section. This makes it possible to override the default WordPress login page. To use the WooCommerce 'my-account' page for login, the login path should be set to '/my-account'
- Increases the priority of the Discourse comments template so that it will be used in place of the comments template that is set through WooCommerce or other plugins
- Adds a `WoocommerceSupport` class that sets the proper redirect from WordPress to Discourse when the WooCommerce `/my-account` page is used as the login page. ~~It also returns the name of the WooCommerce comments_number_filter, and …

FEATURE[WIP]: Improve WooCommerce support

---

css/admin-styles.css
lib/admin.php

Currently, the 'Post types to publish' multi-select is listing all post-types that are available on the site. This includes revisions and attachments and any post types that are added by a plugin. For example, with the WooCommerce plugin activated, that list includes ('revision', 'nav_menu_item', 'product_variation', 'shop_order_refund'...)
This PR adds a post_types_to_publish function that only returns 'public' post types (post, page, attachment, product etc.) For the moment, it excludes 'attachments' from the list. 
There is a filter applied to the return value of the function.

FIX: Post types to publish

---

lib/settings-validator.php

This could be improved. This change allows `/` as a valid path.

Improve login path validation

---

lib/plugin-support/woocommerce_support.php

Return the `discourse_comments_count`. Don't include 'Reply' or 'Replies' with the number.

FIX: return the number of comments

---

css/wp-discourse-styles.css
lib/admin.php
lib/discourse.php
lib/html-templates.php
lib/response-validator.php
lib/settings-validator.php
templates/comments.php
wp-discourse.php

- checks the array returned by `get_post_custom` in `comments.php` before displaying the comments template.
- Adds a `ResponseValidator` class that is used in `discourse.php` and `admin.php`. 
- Periodically checks the connection status with Discourse so that the post's Discourse permalink is not displayed if the forum can't be reached. (Maybe this isn't necessary)

[WIP]: Handle bad response from Discourse

---

uninstall.php

This PR brings `uninstall.php` into compliance with the wp coding standards.

WordPress coding standards uninstall.php

---

lib/html-templates.php

This PR brings `html-templates.php` into compliance with the wp coding standards.

WordPress coding standards html-templates.php

---

lib/admin.php
templates/comments.php

if using SSO, the link that wp-discourse generates that sends the user to the Discourse thread to comment on the WP post ("continue the discussion in our forum"), forces the user to login before they are redirected to the Discourse thread.
i decided that i wanted to have the link redirect straight to the thread without an intervening login page. if the user wants to post when they get there, they can click the "login to reply" button in Discourse.
this patch adds a setting in the admin that allows this behavior (but leaves the default as-is).

Allow redirect to Discourse without login

---

lib/discourse-sso.php

Log the current user out of Discourse before logging them out of WordPress.

Sync logout with Discourse

---

lib/discourse-comment.php
lib/discourse-publish.php

The functions  `sync_comments` and `sync_to_discourse` both set a WordPress transient to avoid making simultaneous api calls to Discourse. The transients are deleted after the api call, but if for some reason the functions calls aren't completed the posts are stuck in a locked state. This PR sets an expiration time on the transients.

FIX: Set expiration on transients

---

composer.json
composer.lock

The updates for composer/installers should not break anything here, at least
while not published with a new major version.
https://github.com/composer/installers/releases
This change helps to manage plugins with composer without manual
conflicts resolving for composer/installers.

Use a less strict version constraint for composer/installers

---

lib/discourse-comment-formatter.php

I was working on adding the comment link in the end of the comments from discourse. This is the solution I came up with.

Allow '{comment_url}' to be used when customizing comments using wpd_comment_body filter

---

lib/discourse-comment-formatter.php
templates/html-templates.php

The default avatar image size and display size (within the comments template) are both 64px. On retina displays this looks blurry. The display can be adjusted smaller or larger than 64px with CSS or by filtering the comment html template (filter: discourse_comment_html). I couldn't figure out another way to adjust the size of the avatar image file besides adding a filter here.
I've created separate filters for posts and participants this time.

Avatar template size filters

---

admin/user-profile.php
lib/sync-discourse-user.php

Headings are typically located outside of the tables for options on WP profile pages. (Thanks Simon!)

Move h2 out of table of user-profile.php

---

lib/sync-discourse-user.php

I was looking for an action hook after we've determined the `$wordpress_user` variable. `wpdc_webhook_user_created` and `wpdc_webhook_user_updated` fire before this happens.
The hook might be more useful after `update_user_data`; either works for me.

Add action hook before update_user_data (webhook)

---

lib/sso-client/client.php

This is deprecated in PHP 7.4.
Fixes #355.

Don't use $array{0} syntax

---

templates/html-templates.php

Comment avatars currently have an empty `alt` attribute - i.e. `alt=""`.
This PR simply adds `Avatar for {username}` for the `alt` description.

Adds alt attribute for comment avatars

---

lib/discourse-comment.php

fixes: https://meta.discourse.org/t/reviews-on-woocommerce-products-disabled-with-discourse-ajax-option/164624

don’t modify comments template for non-discourse post-types

---

lib/utilities.php

1. Adds pagination of ``/groups`` discourse endpoint to ``get_discourse_groups`` Utilities function.
2. Adds generic ``discourse_request`` function for the immediate purpose of 1, and for future use in other Utilities functions.
3. Adds generic ``discourse_munge`` function for the handling of raw data models returned from discourse.

Improvements to get_discourse_groups

---

admin/discourse-sidebar/discourse-sidebar.php

Restricts the client from updating post metadata via the standard wordpress object api. For @scossar.

Restrict client from editing post metadata via standard api

---

lib/discourse-comment.php
readme.txt
wp-discourse.php

This PR adds a `wpdc_comments_count` filter to allow comment counts for posts that have not been published to Discourse to be filtered. That feature was requested by a customer.
The PR also bumps the plugin's version to `2.2.3`

Add wpdc_comments_count filter

---

admin/admin.php
admin/css/admin-styles.css
admin/form-helper.php
admin/js/admin.js
admin/publish-settings.php
admin/settings-validator.php
lib/discourse-publish.php
readme.txt
tests/phpunit/test-discourse-publish.php
wp-discourse.php

For exclude by tag publishing setting
- Uses ajax autocomplete, utilising core wordpress ``tags-box.js``, ``tags-suggest`` and ``ajax-tag-search``
- Use tag slugs instead of ids in ``discourse-publish``

PERF: use ajax tags autocomplete instead of tag list

---

.github/workflows/ci.yml
lib/discourse-comment-formatter.php
lib/discourse.php
lib/plugin-utilities.php
lib/sso-client/client.php
lib/sso-client/sso-client-base.php
readme.txt
templates/html-templates.php
wp-discourse.php

@scossar See https://meta.discourse.org/t/how-to-translate-text-content-in-wp-discourse/202326
~~In draft as this PR needs to be merged first to preserve version sequence: https://github.com/discourse/wp-discourse/pull/421~~

IMPROVE: add translation pipeline for configurable text

---

lib/discourse-comment.php
readme.txt
wp-discourse.php

See https://core.trac.wordpress.org/changeset/43981. Note that the existing usage can cause issues with data attributes used by other plugins, e.g: https://meta.discourse.org/t/discourse-wp-plugin-blocking-paypal-installation-in-easy-digital-downloads-wp-plugin/206172

DEV: data-* attributes are now allowed by default

---

lib/plugin-utilities.php
readme.txt
wp-discourse.php

The new logging feature also introduced consolidating requests into `discourse_request` however, we forgot to ensure that we're using the correct verb for `sync_sso`.

FIX: Use correct verb for sync_sso request

---

.github/workflows/formatting.yml
.github/workflows/metadata.yml
.github/workflows/tests.yml
.gitignore
README.md
docs/COMPOSER.md
docs/FORMATTING.md
docs/contributing.md
package-lock.json
package.json
readme.txt
wp-discourse.php

@scossar This does PR does the following:
- Workflows broken into seperate files: deploy, formatting, metadata and tests.
- Added new metadata workflow that checks if the all the versions have been properly incremented.
See the metadata checks failing here
https://github.com/discourse/wp-discourse/runs/4443780311?check_suite_focus=true
```
Error: Head readme_version is less than or equal to base readme_version.
Error: Head change_version is less than or equal to base change_version.
Error: Head change_date is older than or the same as base change_date.
Error: Head plugin_version is less than or equal to base plugin_version.
Error: Head constant_version is less than or equal to base constant_version.
```
See the metadata checks passing here (after I incremented the versions …

Update workflows and documentation

---

.github/workflows/tests.yml
blocks/comments/comments.php
lib/sso-provider/discourse-sso.php
phpunit.xml
readme.txt
tests/phpunit/multisite.xml
tests/phpunit/test-discourse-publish.php
tests/phpunit/test-sso-client.php
wp-discourse.php

- Fix optional parameter handling in get_discourse_comments.
- Fix compatibility with S3 uploads plugin.
- Fix usage of get_the_excerpt filter.
- Fixed HTML of avatars in quotes in comments.
- Verified backwards compatibility for WP > 5.1.

Two Four Nine

---

lib/discourse-publish.php
tests/phpunit/test-discourse-publish.php

Refactors the `publish_post_after_save` function. It's logic has been broken out into the following protected functions:
- `exclude_post`
- `auto_publish`
- `force_publish_post`
I've included the new protected functions directly under the `publish_post_after_save` function. This was done for readability reasons, but possibly they should be moved lower down in the file.
Some variables have been renamed in the attempt to make it clear at first glance what they are being used for.
None of the underlying logic has been changed.
This PR also removes the unused `post_id` argument from the `has_excluded_tag` function and fixes an issue where `$post_id` was being passed instead of `$post` to that function from the `xmlrpc_publish_post_to_discourse` function.
Possibly some similar changes should …

DEV: Refactor publish_post_after_save function

---

lib/discourse-publish.php
lib/email-notification.php
tests/phpunit/test-discourse-publish.php

Attempts to improve the `xmlrpc_publish_post_to_discourse` method. That method exists for historical reasons. I'm reluctant to remove it entirely, but I suspect that it's not being used on any sites.
This PR also:
- removes the call from `publish_post_after_save` to `update_post_meta( $post_id, 'publish_post_category', intval( $this->options['publish-category'] ) );` for force published posts. That is already being handled in the `sync_to_discourse_work` method.
- moves the call to `sanitize_title( $title )` from `publish_post_after_save` to the  `sync_to_discourse_work` method
- adds a boolean return value to `publish_failure_notification` to allow that method to be easily tested
- changes the EmailNotification object that's used in the DiscoursePublishTest setUp method so that it's a …

DEV: Refactor xmlrpc_publish_post_to_discourse

---

lib/discourse-publish.php
tests/phpunit/test-discourse-publish.php

See further https://meta.discourse.org/t/ampersands-getting-over-escaped-going-from-wordpress-to-discourse/300004

Convert HTML entities in titles before sending to Discourse

---

lib/discourse.php
phpunit.xml
tests/phpunit/multisite.xml

See further https://meta.discourse.org/t/problem-with-use-of-self-in-callables-is-deprecated-in-wp-discourse/297543

Handle PHP deprecations

---

readme.txt
wp-discourse.php

- Add a 'Disable user creation' setting for the DiscourseConnect Client.
- Various package updates, deprecations and minor fixes.
- Convert HTML entites in titles before sending to Discourse.
Live on https://wp-discourse.pavilion.tech/

Two Five Two

---

lib/discourse-publish.php
readme.txt
tests/phpunit/test-discourse-publish.php
wp-discourse.php

- Improve HTML entity decoding in titles.

Two Five Three

---

lib/discourse-comment.php

See https://meta.discourse.org/t/using-wordpress-comments-alongside-discourse/312786

Don't require existing wp comments to show wp comments with setting

---

lib/discourse-publish.php
tests/phpunit/test-discourse-publish.php

See further: https://meta.discourse.org/t/bug-in-wordpress-plugin-quick-edit-forces-old-topics-to-be-pushed/336882

FIX: Don't auto-publish quick edits
